[versions]
smarthome-api = "2026.08-SNAPSHOT"
smarthome-domain = "2026.09-SNAPSHOT"
smarthome-hub = "2026.09-SNAPSHOT"

buildconfig = "6.0.10"

detekt = "2.0.0-alpha.6"

jvm-toolchain = "21"

logback = "1.6.3"

koin = "4.2.2"

kotlin = "2.4.10"
kotlin-coroutines = "1.11.0"
kotlin-expect = "0.2"
kotlin-kover = "0.9.9"
kotlin-logging = "8.0.4"

ktlint = "1.8.0"

ktor = "3.5.2"

oshi = "6.9.0"

slf4j = "2.0.18"

test-balloon = "1.0.1-K2.4.0"

turbine = "1.2.1"

[libraries]
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor" }

kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-expect-core = { group = "dev.nmarsman.expect", name = "kotlin-expect-core", version.ref = "kotlin-expect" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlin-logging" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-api-key = { group = "io.ktor", name = "ktor-server-auth-api-key", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-forwarded-header = { group = "io.ktor", name = "ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

oshi-core = { group = "com.github.oshi", name = "oshi-core", version.ref = "oshi" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

smarthome-api = { group = "network.marsys.smarthome", name = "smarthome-api", version.ref = "smarthome-api" }
smarthome-domain = { group = "network.marsys.smarthome", name = "smarthome-domain", version.ref = "smarthome-domain" }

test-balloon-core = { group = "de.infix.testBalloon", name = "testBalloon-framework-core", version.ref = "test-balloon" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }

detekt = { id = "dev.detekt", version.ref = "detekt" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlin-kover" }

ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

test-balloon = { id = "de.infix.testBalloon", version.ref = "test-balloon" }

[bundles]
kotlin-logging = ["kotlin-logging", "slf4j-api", "logback-classic"]
